### ISSUE TITLE
brew安装报错

### ISSUE THREAD

**Issue by sukeyisme** [xcodebuild/fcitx-remote-for-osx#15]
命令：brew install fcitx-remote-for-osx --with-input-method=squirrel-rime
结果：
==> Downloading https://github.com/CodeFalling/fcitx-remote-for-osx/archive/0.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/fcitx-remote-for-osx-0.1.0.tar.gz
==> ./build.py build
Last 15 lines from /Users/sukey/Library/Logs/Homebrew/fcitx-remote-for-osx/01.build.py:
2016-05-26 10:53:43 +0800

./build.py
build

Traceback (most recent call last):
  File "./build.py", line 59, in <module>
    build(sys.argv[2])
  File "./build.py", line 26, in build
    use_opts = OPTS % (InputMethod[imname], use_path)
KeyError: ''

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

如果直接：brew install fcitx-remote-for-osx 不加输入法 不会报错

**Comment by jiegec** [comment]
Seems that brew made some changes to ARGV:

```
ARGV only contains ["/usr/local/Library/Taps/homebrew/homebrew-core/Formula/fcitx-remote-for-osx.rb", "--verbose", "--with-input-method="]
```

Audit says: Use build instead of ARGV to check options. I do not know how to, though. Need to bisect and report it to homebrew maintainers. Or else we can supply the options as --with-baidu-pinyin, --with-squirrel-rime, etc.

@CodeFalling Time to test your English.
